require:
  - rubocop-rails
  - rubocop-performance

inherit_from: .rubocop_todo.yml

Layout/LineLength:
  Max: 130
  AllowURI: true

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - "config/environments/production.rb"

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 50

Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Rails/ReflectionClassName:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false
  Exclude:
    - "spec/**/*"
    - "test/**/*"
    - "app/helpers/application_helper.rb"
    - "app/mailers/application_mailer.rb"
    - "app/models/application_record.rb"
    - "config/application.rb"

Style/FormatStringToken:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Lambda:
  EnforcedStyle: literal

Style/MixinUsage:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Exclude:
    - "config/application.rb"
    - "config/environments/production.rb"
    - "config/puma.rb"

Style/SymbolArray:
  EnforcedStyle: brackets

AllCops:
  Exclude:
    - "bin/*"
    - "node_modules/**/*"
    - "db/*.rb"
    - "db/migrate/*.rb"
    - "vendor/**/*"
    - ".git/**/*"
    - "Gemfile"
